SELECT l.LISSITE,
       COUNT(*) AS NB_LIENS,
       MIN(l.LISDDEB) AS DATE_DEBUT,
       MAX(l.LISDFIN) AS DATE_FIN FROM V5PROD.LIENSERV l WHERE l.LISSITE = 7120 AND TRUNC(SYSDATE) BETWEEN l.LISDDEB AND l.LISDFIN GROUP BY l.LISSITE